name: akepot
description: A competence matrix
dependencies:
  browser: any
  core_elements: ">=0.5.0 <0.7.0"
  paper_elements: ">=0.6.0+3 <0.7.0"
  polymer: ">=0.15.1+5 <0.16.0"
  intl: any
  sass: any
transformers:
- sass:
    compass: true                 # Include compass
- polymer:
    entry_points:
    - web/akepot.html
- $dart2js:
    checked: true
    minify: false
    verbose: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    csp: true