name: 'akepot'
version: 0.0.1
description: A competence matrix
author: pjv <ezelspinguin@gmail.com>
homepage: https://competencematrix.com

environment:
  sdk: '>=1.18.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  observe: any
  polymer_elements: ^1.0.0-rc.9
  polymer: ^1.0.0-rc.18
  template_binding: ^0.14.0
  web_components: ^0.12.0
  #reflectable: ^1.0.0
  intl: any
  sass: any
transformers:
- sass:
    compass: false                 # Include compass
- web_components:
    entry_points:
    - web/akepot.html
#- reflectable:
#    entry_points:
#    - web/akepot.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
#- $dart2js:
#    checked: false
#    minify: true
#    verbose: false
#    suppressWarnings: false
#    suppressHints: false
#    terse: false
#    csp: false

#dependency_overrides:
#  polymer:
#    git:
#      ref: b66389b
#      url: https://github.com/dart-lang/polymer-dart.git
#  polymer_elements:
#    git:
#      ref: v1.0.0-rc.9
#      url: https://github.com/dart-lang/polymer_elements.git
#  polymer_interop:
#    git:
#      ref: 0.2.0-dev
#      url: https://github.com/dart-lang/polymer_interop.git