name: 'akepot'
version: 0.0.1
description: A competence matrix
author: pjv <ezelspinguin@gmail.com>
homepage: https://competencematrix.com

environment:
  sdk: '>=1.18.0 <2.0.0'

dependencies:
  browser: any
  observe: any
  polymer_elements: ^1.0.0-rc.9
  polymer: ^1.0.0-rc.18
  template_binding: any
  web_components: any
  sass: any
  firebase:
    path: ../firebase-dart
transformers:
- sass:
    compass: true
- polymer:
    entry_points:
    - web/index.html

- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
