name: akepot
description: A competence matrix
dependencies:
  browser: any
  core_elements: ">=0.6.0+1 <0.7.0"
  paper_elements: ">=0.6.0+3 <0.7.0"
  polymer: ">=0.15.3+2 <0.16.0"
  intl: any
  sass: any
  google_signin_dart: any
  app_router: any
#  app_router:
#    path: ../app_router_dart
  pushstate_anchor: any
transformers:
- sass:
    compass: true                 # Include compass
- polymer:
    entry_points:
    - web/akepot.html
- $dart2js:
    checked: false
    minify: true
    verbose: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    csp: false