name: akepot
description: A competence matrix
dependencies:
  browser: any
  core_elements: any
  paper_elements: any
  polymer: ">=0.15.1+5 <0.16.0"
  intl: any
  sass: any
  google_oauth_authenticator: ">=1.0.0 <2.0.0"
  more_routing_dart:
    path: /Data/CR/dart/more_routing/
transformers:
- sass:
    compass: true                 # Include compass
- polymer:
    entry_points:
    - web/akepot.html
- $dart2js:
    checked: true
    minify: false
    verbose: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    csp: true