name: akepot
description: A competence matrix
dependencies:
  browser: any
  core_elements: ">=0.7.1+2 <0.8.0"
  paper_elements: ">=0.7.1+1 <0.8.0"
  polymer: ">=0.16.3+3 <0.17.0"
  intl: any
  sass: any
#  app_router: any
  app_router:
    path: ../app_router_dart
  pushstate_anchor:
    path: ../pushstate_anchor_dart
#  json_object: '>=1.0.19 <1.1.0'
  firebase:
    path: ../firebase-dart
transformers:
- sass:
    compass: true                 # Include compass
- polymer:
    entry_points:
    - web/akepot.html
#- $dart2js:
#    checked: false
#    minify: true
#    verbose: false
#    suppressWarnings: false
#    suppressHints: false
#    terse: false
#    csp: false