name: akepot
description: A competence matrix
dependencies:
  browser: any
  core_elements: any
  paper_elements: any
  polymer: ">=0.15.1+5 <0.16.0"
  intl: any
  sass: any
  google_oauth2_client: '>=0.3.4'
transformers:
- sass:
    compass: true                 # Include compass
- polymer:
    entry_points:
    - web/akepot.html