# Cli launch configuration for build.dart.
type: cli
path: build.dart

cli:
  # Additional args for the application.
  args:
  # The working directory to use for the launch.
  cwd:
  # Enable or disable checked mode.
  checked: true
  # Enable or disable debugging.
  debug: true
